### ISSUE TITLE
Impossibile to build without GNU C libs

### ISSUE THREAD

**Issue by shatteringlass** [2ion/forecast#4]
I tried to make this on my Mac and this is the terminal output:  

```bash
$ make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/local/Cellar/json-c/0.12/include/json-c  -I/usr/local/Cellar/libconfig/1.5/include   -I/usr/local/opt/ncurses/include  -I/usr/local/Cellar/lz4/r131/include  -g -O2 -MT forecast-forecast.o -MD -MP -MF .deps/forecast-forecast.Tpo -c -o forecast-forecast.o `test -f 'forecast.c' || echo './'`forecast.c
In file included from forecast.c:26:
In file included from ./cache.h:15:
./forecast.h:24:10: fatal error: 'error.h' file not found
#include <error.h>
         ^
1 error generated.
make[2]: *** [forecast-forecast.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
``` 

This is because BSD and OSX don't have this <error.h> and other headers included in glibc. Are you planning to make this portable? thanks

**Comment by 2ion** [comment]
You are correct that this currently doesn't build against other C libraries. This is not exactly intentional but more of a side effect of cheerfully using whatever function came my way.

The error you are seeing in particular is due to my use of error_at_line() in the LERROR() macro in `forecast.h`, which is used both as an error handler and a logging/reporting function practically everywhere. You could try and implement the macro in terms of standard library functions as a temporary solution. There might be caveats though.

I'm not sure if I rely on GNU-specific stuff elsewhere.

I'm occupied until late November, I'll attempt to make the program compatible with other C libraries after then. Nothing can happen in the short run, sorry. I'm leaving this issue open until this is resolved.

Quick question: In order to be able to build the program on OSX, is it sufficient to just make it compatible with NetBSD or are there other differences (I have no OSX machine for testing)?

**Comment by shatteringlass** [comment]
Thanks for the quick reply. I'm really looking forward to using this without the need for a VM. I think NetBSD would be a good benchmark, otherwise I could try and compile for you.

**Comment by 2ion** [comment]
Confirmed successful build on OSX 11.10. A few build notes:
* Almost all of the libraries need to be installed using homebrew.
* Configure needed to be run with `export PKG_CONFIG=$(which pkg-config)` so that it could find the pkg-config binary, no idea why this wasn't set by default.
* Compiling forecastfs on OSX will be enabled a) as soon as it is done and b) when it has been tested against OSXfuse.

Here's some data on the shared binary:
```
/usr/local/bin/forecast:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /usr/local/opt/json-c/lib/libjson-c.2.dylib (compatibility version 3.0.0, current version 3.1.0)
        /usr/local/opt/libconfig/lib/libconfig.9.dylib (compatibility version 12.0.0, current version 12.0.0)
        /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
        /usr/local/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
        /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/local/opt/lz4/lib/liblz4.1.dylib (compatibility version 1.0.0, current version 1.7.1)
        /usr/local/opt/talloc/lib/libtalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
```

**Comment by shatteringlass** [comment]
Sweet, thanks!
